export const baseurl='http://localhost:8000/'
export const METABASE_URL = "http://localhost:3000";
export const Login = baseurl+'api/usr/login-page';
export const Register = baseurl+'api/usr/registerteacher';
export const RegisterSchool = baseurl+'api/usr/registerschool';
export const TeacherRegister = baseurl+'api/usr/teacherregisterteacher';
export const RegisterStudent = baseurl+'api/usr/registerstudent';
export const BulkRegisterStudents = baseurl+'api/usr/bulkstudentenrollment';
export const agegrouptoppers=baseurl+'api/cmp/GetAgeGroupToppers'
export const BulkRegister = baseurl+'api/usr/bulkregisterstudent';
export const schoolGroupNames = baseurl+'api/com/schoolGroupnames';
export const CountryNames = baseurl+'api/com/countrynames';
export const StateNames = baseurl+'api/com/statenames';
export const DistrictNames = baseurl+'api/com/districtnames';
export const Logout =baseurl+'api/usr/logout-page';
export const SchoolNames = baseurl+'api/com/schoolnames';
export const SchoolClasses = baseurl+'api/com/schoolclasses';
export const Cmp_Names = baseurl+'api/com/cmpnames';
export const getUsers = baseurl+'api/usr/userdata';
export const SchoolTeacher = baseurl+'api/auth/teacherschool';
export const StudentDataExcel=baseurl+'api/usr/getuserdataexcel';
export const ResetPasswordViewurl = baseurl+'api/usr/ResetPasswordView';
export const ConfirmResetPasswordViewurl = baseurl+'api/usr/ConfirmResetPasswordView';
export const ChangePasswordView = baseurl+'api/usr/ChangePasswordView';
export const ContactUsMail = baseurl+'api/usr/ContactUsMail';
export const UserResult = baseurl+'api/usr/userresult';
export const AllUsersResults = baseurl+'api/usr/Alluserresult';
export const CompetitionList = baseurl+'api/cmp/cmpnames'
export const CompetitionListforCertificate = baseurl+'api/com/cmpnamesforcertificate'
export const CompetitionQues=baseurl+'api/cmp/getcmp'
export const CompetitionNameResultList = baseurl+'api/cmp/getcmpnamesResults'
export const CompetitionNameAnalysisList = baseurl+'api/cmp/getcmpnamesAnalysis'
export const CompetitionResultList = baseurl+'api/cmp/getcmpResults'
export const CompetitionStudentResponse = baseurl+'api/cmp/studentResponse'
export const calcTotalScore = baseurl+'api/cmp/calcTotalScore'
export const getLanguages = baseurl+'api/cmp/getLang'
export const PracticeChallengeList = baseurl+'api/cmp/getpracticeChallengeNames'
export const PracticeChallengeQues=baseurl+'api/cmp/getPracChallengeQuestionAPI'
export const Certificatesforselectedstudents=baseurl+'api/cmp/GetParticipationCertificatesforSelectedStudents'
export const DeleteFiles=baseurl+'api/cmp/deleteFilesandZip'
export const ParticipationCertificatesforStudentPortal=baseurl+'api/cmp/GetParticipationCertificatesforStudentPortal'
export const SchoolTopperCertificates=baseurl+'api/cmp/SchoolTopperCertificates'
export const ParticipationCertificates=baseurl+'api/cmp/ParticipationCertificates'
export const FetchCertificate=baseurl+'media/ZipFolder/BebrasCertificate.zip'
export const schoolTypes=baseurl+'api/com/getschooltypenames'
export const genderoptions=baseurl+'api/com/getgendernames'